@startuml
abstract class BaseActor {
    + Components : Dictionary<Type,object>
    + SceneObject : GameObject
    + <<virtual>> IsActive : bool <<get>> <<set>>
    + AddComponent(_component:object) : void
    + GetComponent<T>() : T
    + <<virtual>> Update() : void
    + <<virtual>> FixedUpdate() : void
    # <<virtual>> InitializeActor() : void
}
IActor <|.. BaseActor
IUpdateable <|.. BaseActor
@enduml
