@startuml
abstract class AbstractState {
    + OwnerData : Scratchpad <<get>>
    # OwnerStateMachine : StateMachine <<get>>
    # AbstractState(_ownerData:Scratchpad, _ownerStateMachine:StateMachine)
    + <<virtual>> OnEnter() : void
    + <<virtual>> OnUpdate() : void
    + <<virtual>> OnFixedUpdate() : void
    + <<virtual>> OnExit() : void
}
IState <|-- AbstractState
@enduml
