@startuml
class PlayState {
    + <<override>> OnEnter() : void
    + <<override>> OnUpdate() : void
    + <<override>> OnFixedUpdate() : void
    + <<override>> OnExit() : void
}
AbstractState <|-- PlayState
PlayState *-up- EnemyManager
PlayState *---> Player
PlayState *---> WeaponHandler
PlayState *--> Timer
@enduml
