@startuml
abstract class BaseActor {
    + SceneObject : GameObject <<get>> <<protected set>>
    + Components : Dictionary<Type, object> <<get>>
    - isActive : bool = true
    + IsActive : bool <<get>> <<set>>
    + AddComponent(_component:object) : void
    + GetComponent() : T
    + <<virtual>> Update() : void
    + <<virtual>> FixedUpdate() : void
    + <<virtual>> Destroy() : void
    # <<virtual>> InitializeActor() : void
}
IActor <|-- BaseActor
IUpdateable <|-- BaseActor
IDestroyable <|-- BaseActor
@enduml
