@startuml
class Enemy {
    + Health : float <<get>>
    + PointValue : float <<get>>
    + Enemy(_instance:GameObject)
    + Initialize(_enemyData:EnemyData) : void
    + TakeDamage(_damage:float) : void
}
BaseActor <|-- Enemy
IDamageable <|-- Enemy
@enduml
