@startuml
class "ObjectPool<T>"<T:IPoolable> {
    + RequestObject() : T
    + ReturnObjectToPool(_item:T) : void
    + ReturnAllObjectsToPool(\n  _event:ObjectPoolResetEvent) : void
}
IPoolable o-- "ObjectPool<T>"
@enduml
