@startuml
class StateWallRunning {
    + <<override>> OnEnter() : void
    + <<override>> OnUpdate() : void
    + <<override>> OnFixedUpdate() : void
    + <<override>> OnExit() : void
}
AbstractState <|-- StateWallRunning
@enduml
