@startuml
class StateWalking {
    walkForce : float = 10.0f
    + <<override>> OnEnter() : void
    + <<override>> OnUpdate() : void
    + <<override>> OnFixedUpdate() : void
    + <<override>> OnExit() : void
}
AbstractState <|-- StateWalking
@enduml
