@startuml
class Projectile {
    + ReturnToPool : Delegate
    + Initialize(_projectileData:ProjectileData) : void
    + <<override>> FixedUpdate() : void
    + OnEnableObject() : void
    + OnDisableObject() : void
}
BasePhysicsActor <|--- Projectile
IPoolable <|.. Projectile
ProjectileData <-- Projectile
@enduml
