@startuml
class PlayerWeapon<(_weaponData:WeaponData, \n_projectilePool:ObjectPool<Projectile>)> {
    + IsAutomatic : bool <<get>>
    + Fire() : void
}
"ObjectPool<T>" <-- PlayerWeapon
WeaponData <-- PlayerWeapon
BaseActor <|-- PlayerWeapon
PlayerWeapon *-- Timer
@enduml
