@startuml
class WeaponHandler {
    + IsActive : bool <<get>> <<set>>
    + WeaponHandler(_weaponDataAssets:WeaponData[])
    + Update() : void
    + FixedUpdate() : void
}
IUpdateable <|.. WeaponHandler
WeaponHandler *-- "ObjectPool<T>"
@enduml
